version: '3'
services:
  web:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "3080:3000"
    volumes:
      - .:/home/node/app
    command: /home/node/app/app_init
